[build]
  base    = "landing-page"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from   = "/v3/*"
  to     = "/v3/index.html"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
